Repository aggie-coding-club/club-website, pull requests merged in 2018-08, with the labels that each got.

#62 Removed the dependency on "config.json" from the scrape_github manage…
  requirements.txt
  server/github/management/commands/__pycache__/scrape_github.cpython-36.pyc
  server/github/management/commands/scrape_github.py
  server/github/migrations/0002_auto_20180813_1617.py
  server/github/migrations/__pycache__/0001_initial.cpython-36.pyc
  server/github/migrations/__pycache__/__init__.cpython-36.pyc
  server/github/serializers.py
Labels: back-end

#63 Fixed issues with project assignment management commands
  requirements.txt
  server/github/admin.py
  server/github/management/commands/__pycache__/scrape_github.cpython-36.pyc
  server/github/management/commands/config-example.json
  server/github/migrations/__pycache__/0001_initial.cpython-36.pyc
  server/github/migrations/__pycache__/__init__.cpython-36.pyc
  server/github/models.py
  server/projects/management/commands/assign_members_to_teams.py
  server/projects/migrations/0003_auto_20180802_0259.py
  server/projects/models.py
  server/projects/serializers.py
  server/projects/tests/__init__.py
  server/projects/tests/management_commands_tests/__init__.py
  server/projects/tests/management_commands_tests/assign_members_to_teams_tests.py
  server/projects/tests/managers_tests/__init__.py
  server/projects/tests/managers_tests/project_application_manager_tests.py
  server/projects/tests/managers_tests/project_manager_tests.py
  server/projects/tests/models_tests/__init__.py
  server/projects/tests/models_tests/project_application_model_tests.py
  server/projects/tests/models_tests/project_model_tests.py
  server/projects/tests/shared_testcase.py
  server/projects/tests/views_tests/__init__.py
  server/projects/tests/views_tests/project_views_tests.py
  server/projects/urls.py
  server/projects/views.py
  server/server/settings.py
  server/server/urls.py
Labels: bug

#65 Created events models.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  server/events/__init__.py
  server/events/admin.py
  server/events/apps.py
  server/events/migrations/0001_initial.py
  server/events/migrations/__init__.py
  server/events/models.py
  server/events/tests/__init__.py
  server/events/tests/shared_case.py
  server/events/tests/test_models.py
  server/events/views.py
  server/server/settings.py
Labels: back-end

#64 Created notifications models.
  .gitignore
  server/github/management/commands/__pycache__/scrape_github.cpython-36.pyc
  server/github/migrations/__pycache__/0001_initial.cpython-36.pyc
  server/github/migrations/__pycache__/__init__.cpython-36.pyc
  server/notifications/__init__.py
  server/notifications/admin.py
  server/notifications/apps.py
  server/notifications/migrations/0001_initial.py
  server/notifications/migrations/0002_auto_20180813_1849.py
  server/notifications/migrations/0003_auto_20180813_1850.py
  server/notifications/migrations/0004_auto_20180814_2245.py
  server/notifications/migrations/__init__.py
  server/notifications/models.py
  server/notifications/services.py
  server/notifications/tests/__init__.py
  server/notifications/tests/models_tests/__init__.py
  server/notifications/tests/models_tests/emailnotification_tests.py
  server/notifications/tests/models_tests/slackemailnotification_tests.py
  server/notifications/tests/models_tests/slacknotification_tests.py
  server/notifications/tests/services_tests.py
  server/notifications/tests/shared_testcase.py
  server/notifications/views.py
  server/projects/services.py
  server/projects/tests/__init__.py
  server/projects/tests/services_tests.py
  server/server/settings.py
  server/templates/emails/project_allocation.html
Labels: back-end, help wanted
